function str = strrepPaper(str)

patrep = {'T20','Ae-T';...
    'C20','Ae-C';...
    'C25','Ae-c';...
    '','A.th';...
    'Minus65','P.ab-M';...
    'Plus65','P.ab-P';...
    'R143','PP-R';...
    'G129','PP-G';...
    'arabidopsis','A.th';...
    ' ','-'};

for i=1:size(patrep,1)
    str = strrep(str,patrep{i,1},patrep{i,2});
end


